seed: 101
debug: False # set debug=False for Full Training
exp_name: 'TimesUnet-6'
comment: 'TimesUnet'
model_name: 'TimesUnet'
backbone: 'vgg16'
train_bs: 32
valid_bs: 32
debug_train_bs: 10
debug_valid_bs: 10
img_size: [320, 384]
epochs: 20
lr: 0.001
scheduler: 'CosineAnnealingLR'
min_lr: 0.000001
T_max: int(30000/train_bs*epochs)+50
T_0: 40
warmup_epochs: 0
wd: 0.000001
n_accumulate: max(1, 32//train_bs)
n_fold: 5
num_classes: 3
use_channel_attention : True
use_timestamp : True
use_DBM: True
attention: 'scse'
lambda_ : 1
2.5D: True

